### ISSUE TITLE
No such file or directory: 'sample/clean.wav'?

### ISSUE THREAD

**Issue by Lynlzz1314** [bill9800/Speech-denoise-Autoencoder#1]
Hi, 
   bill9800. There are some errors when I run the  denoise-autoencoder.py
File "denoise-autoencoder.py", line 48, in <module>
    with open('sample/clean.wav', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sample/clean.wav'

**Comment by bill9800** [comment]
I modify sox command line in conc function under AVhandler. The problem might come from the difference of sox versions.  

For your reference, here are some other possible ways to solve your problem.
1. try to run the download part again, not sure why sox somtimes did not work properly on the first wav file.
2. upgrade the youtube-dl according to the step in https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl. 
3. upgrade ffmpeg -- **sudo apt upgrade ffmpeg**
